# Generated by Django 3.1.3 on 2020-11-07 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('style', models.CharField(choices=[('radio', 'radio'), ('slider', 'slider'), ('autocomplete', 'autocomplete'), ('multiple', 'multiple')], default='radio', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=400)),
                ('followup_question', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.question')),
            ],
        ),
    ]
