# Generated by Django 3.1.3 on 2020-11-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20201107_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.FloatField(default=1),
        ),
    ]
