# Generated by Django 3.1.3 on 2020-11-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_question_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='followup_question',
        ),
        migrations.AddField(
            model_name='answer',
            name='followup_question',
            field=models.ManyToManyField(blank=True, default=None, to='questionnaire.Question'),
        ),
    ]
