# Generated by Django 3.1.3 on 2020-11-07 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201106_2347'),
        ('questionnaire', '0006_questionnaireresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresult',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_result', to='profiles.profile'),
        ),
    ]
