version: "3.3"
   
services:
  server:
    build: .
    command: bash -c "python manage.py migrate; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=server.settings_prod

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=junction
      - POSTGRES_PASSWORD=junction
      - POSTGRES_DB=junction

volumes:
   postgres_data:
